version: "3.8"
services:
   sample-webserver:
      container_name: "myReactapp"
      hostname: "myReactapp"
      restart: always
      networks:
         - "sample-react"
      ports:
         - "3000:3000"
      build:
         context: "$PWD/web"
      image: react-sample
   sample-webserver-nginx:
      container_name: "myReactapp-lb"
      hostname: "myReactapp-lb"
      volumes:
        - "$PWD/nginx/conf:/etc/nginx"
      restart: always
      networks:
            - "sample-react"
      ports:
         - "80:80"
      build:
         context: "$PWD/nginx"
      image: react-sample_nginx
      command: [nginx-debug, '-g', 'daemon off;']
networks:
  sample-react:
  

