version: "3.8"
services:
   sample-webserver:
      container_name: "sample-webserver"
      hostname: sample-webserver
      restart: always
      networks:
         - "sample-react"
      ports:
         - "3000:3000"
      build:
         context: "$PWD/web"
      image: react-sample
   sample-webserver-nginx:
      container_name: "sample-webserver_nginx"
      hostname: sample-webserver-nginx
      volumes:
        - "$PWD/nginx/conf:/etc/nginx"
        - "$PWD/nginx/certs:/etc/ssl/private"
      restart: always
      networks:
            - "sample-react"
      ports:
         - "80:80"
         - "443:443"
      build:
         context: "$PWD/nginx"
      image: react-sample_nginx
      command: [nginx-debug, '-g', 'daemon off;']
   sample-webserver-db:
        container_name: "sample-webserver_db"
        hostname: sample-webserver-db
        volumes:
            - "$PWD/db:/data/db"
        restart: always
        ports:
            - "27017:27017"
        image: mongo
        command: "mongod --noauth --smallfiles"
        networks:
            - "sample-react"
networks:
  sample-react:
  

